---
title: "Election x Twitter"
output: 
  html_document:
    after_body: footer.html
---

### Subtitle

Image / Text


## Motivation

US polls have been the center of attention in recent presidential elections due to the fact that the results have not accurately reflected predictions ([US PresidentialElection Polls Failure](https://news.northeastern.edu/2020/11/04/the-polls-were-still-way-off-in-the-2020-election-even-after-accounting-for-2016s-errors/)). 
Pollsters suggest that the evidence of the 2016 and 2020 elections will improve polling models. 

On the other hand, the evolution of social media has been tied to political behavior such as voting ([Twitter as Indicator for Political Behavior](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0079449)). Since the public is quickly losing the trust of polls for political elections, researchers are now exploring whether social media activity can be utilized to assess offline political behavior. We believe that extracting online social networking environments can shed light on communication patterns and political preferences of individuals.

We hypothesize that social media (within the US and potentially outside of the US) can be beneficial in identifying elelectoral behaviors. We want to use Twitter (specifically geocoding tweets referencing presidential candidates) to identify the political affiliation to that region. 

## Data Sources

[US Election Twitter ](https://www.kaggle.com/manchunhui/us-election-2020-tweets)

[2020 Election Forecast](https://github.com/fivethirtyeight/data/tree/master/election-forecasts-2020)

[2020 Election](https://www.kaggle.com/unanimad/us-election-2020)

A brief screencast of our project can be found [here](link to screencast).

&nbsp;
<hr />
<p style="text-align: center;"><a href="">Chankasaul, Jr</a> | <a href="">de Araujo, Thiago</a> | <a href="">Kao, Chia-Wen</a>| <a href="">Ostropolets, Anna</a></p>

<p style="text-align: center;"> 2020 </p>
