---
title: "2020 Election Polls"
output: 
  html_document:
    source: embed
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)
library(patchwork)
```

```{r clean_datasets, echo=FALSE, message=FALSE, warning=FALSE}

##Clean Polls and Regional datasets 

polls_df=
  read_csv("./datasets/presidential_state_toplines_2020.csv") %>%
  rename(date = modeldate) %>% 
  mutate(date = as.Date (date, format = "%m/%d/%Y"))%>% 
  separate(date, into = c("year", "month", "day")) %>%  
   select(state, month, day, candidate_chal,
          winstate_chal, voteshare_chal,
          candidate_inc, winstate_inc, voteshare_inc, 
          margin, state_turnout,
          -candidate_chal, -candidate_inc) %>% 
  rename(
    biden_winstate = winstate_chal, 
    biden_voteshare = voteshare_chal,
    trump_winstate = winstate_inc, 
    trump_voteshare = voteshare_inc, 
    voteshare_margin = margin,
    expvote_turnout = state_turnout) %>% 
  arrange(state, month, day)

region_df = 
    read_csv("./datasets/states.csv") %>% 
    rename(state = State)  

## Merge Polls and Regional Data 
polls_merge =
    merge(
    polls_df,
    region_df,
    by = "state") %>% 
  arrange(state, month, day) %>% 
  select(-`State Code`) %>% 
  relocate("state", "Region") %>% 
  view ()
```


```{r Clean_Voter_Data, echo=FALSE, message=FALSE, warning=FALSE}

## Clean vote proportion and number of votes for each candidate by state

exp_votes=
  polls_merge %>%
  select (-trump_winstate, -biden_winstate, -voteshare_margin, -Division) %>%
  filter (month == 11) %>% 
  rename (State = state) %>% 
  group_by(Region, State, month) %>%     
  summarize(
    voter_turnout = mean(expvote_turnout),
    prop_Biden = mean(biden_voteshare),
    prop_Trump = mean(trump_voteshare)
    ) %>% 
  pivot_longer(
      prop_Biden:prop_Trump,
      names_to = "Candidate", 
      names_prefix = "prop_",
      values_to = "votes_proportion") %>% 
  mutate(
    candidate_votes = (votes_proportion/100)*voter_turnout
    ) 
  
```


Text describing Expected votes 



```{r Expected_Total_Votes, echo=FALSE, message=FALSE, warning=FALSE}

## Below is expected voter turnout taking the mean of the first 3 days of November by State  

## Midwestern States 
expvote_plot1 = 
  exp_votes %>%
    filter(Region == "Midwest") %>% 
    ggplot(aes(x = reorder(State, desc(voter_turnout)), y = voter_turnout/1000000)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='steelblue') +
      labs(
        title = "Expected Votes in Midwestern States", 
        x = "State", 
        y = "Total Votes (M)") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

## Western States 
expvote_plot2 = 
  exp_votes %>%
    filter(Region == "West") %>% 
    ggplot(aes(x = reorder(State, desc(voter_turnout)), y = voter_turnout/1000000)) +
    geom_bar(stat = "identity", position = position_dodge(), 
             fill='steelblue') +
      labs(
        title = "Expected Votes in Western States", 
        x = "State", 
        y = "Total Votes (M)") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

## Northeastern States 
expvote_plot3 = 
  exp_votes %>%
    filter(Region == "Northeast") %>% 
    ggplot(aes(x = reorder(State, desc(voter_turnout)), y = voter_turnout/1000000)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='steelblue') +
      labs(
        title = "Expected Votes in Northeastern States", 
        x = "State", 
        y = "Total Votes (M)") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

## Southern States 
expvote_plot4 = 
  exp_votes %>%
    filter(Region == "South") %>% 
    ggplot(aes(x = reorder(State, desc(voter_turnout)), y = voter_turnout/1000000)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='steelblue') +
      labs(
        title = "Expected Votes in Southern States", 
        x = "State", 
        y = "Total Votes (M)") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

## Plot of expected voter turnout for all US States 
expvote_plot1 + expvote_plot2 + expvote_plot3 + expvote_plot4

## Decimal Places 
options(scipen = 999)
```

Text describing Proportion of votes per candidate 


```{r Candidate_Prop_Votes, echo=FALSE, message=FALSE, warning=FALSE}
colors <- c("dark red", "dark blue")
names(colors) = c("Trump", "Biden")

mid_prop =
exp_votes %>% 
    filter(Region == "Midwest") %>% 
    ggplot(aes(x = State, y = round(votes_proportion,2), fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "Midwest", 
         y = "Vote Proportion") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

west_prop =
exp_votes %>% 
    filter(Region == "West") %>% 
    ggplot(aes(x = State, y = round(votes_proportion,2), fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "West", 
         y = "Vote Proportion") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

south_prop=
exp_votes %>% 
    filter(Region == "South") %>% 
    ggplot(aes(x = State, y = round(votes_proportion,2), fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "South", 
         y = "Vote Proportion") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

northeast_prop=
exp_votes %>% 
    filter(Region == "Northeast") %>% 
    ggplot(aes(x = State, y = round(votes_proportion,2), fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "Northeast", 
         y = "Vote Proportion") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

## Combine Proportion Plots 
mid_prop + south_prop + west_prop + northeast_prop + plot_layout(guides = "collect")

```


Text describing raw votes by state for each candidate 

```{r Candidate_Total_Votes, echo=FALSE, message=FALSE, warning=FALSE}
colors <- c("dark red", "dark blue")
names(colors) = c("Trump", "Biden")

mid_plot =
exp_votes %>% 
    filter(Region == "Midwest") %>% 
    ggplot(aes(x = State, y = candidate_votes/1000000, fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "Midwest", 
         y = "Number of Votes(M)") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

west_plot =
exp_votes %>% 
    filter(Region == "West") %>% 
    ggplot(aes(x = State, y = candidate_votes/1000000, fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "West", 
         y = "Number of Votes(M)") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

south_plot=
exp_votes %>% 
    filter(Region == "South") %>% 
    ggplot(aes(x = State, y = candidate_votes/1000000, fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "South", 
         y = "Number of Votes(M)") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

northeast_plot=
exp_votes %>% 
    filter(Region == "Northeast") %>% 
    ggplot(aes(x = State, y = candidate_votes/1000000, fill = Candidate)) +
    geom_bar(stat = "identity", position = position_dodge()) + 
    labs(x = "Northeast", 
         y = "Number of Votes(M)") + 
    scale_fill_manual(values = colors) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

## Combine raw votes per state for each candidate 
mid_plot + south_plot + west_plot + northeast_plot + plot_layout(guides = "collect")
```


Text describing voter margin by state for each candidate 

```{r Voteshare_Margin, echo=FALSE, message=FALSE, warning=FALSE}

vote_margin=
  polls_merge %>% 
  select (state, Region, month, day, voteshare_margin) %>% 
  drop_na() %>% 
  group_by(Region, state, month) %>%     
  summarize(
    month_avg = mean(voteshare_margin)) %>% 
  filter(month == 11) 

margin_plot1 = 
  vote_margin %>%
  filter(Region == "South") %>% 
    ggplot(aes(x = reorder(state, desc(month_avg)), y = month_avg)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='dark green') +
    labs(
        title = "Trump's Margin", 
        x = "Southern States", 
        y = "Percent Difference") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

margin_plot2 = 
  vote_margin %>%
  filter(Region == "West") %>% 
    ggplot(aes(x = reorder(state, desc(month_avg)), y = month_avg)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='dark blue') +
    labs(
        title = "Trump's Vote Margin", 
        x = "Western States", 
        y = "Percent Difference") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

margin_plot3 = 
  vote_margin %>%
  filter(Region == "Northeast") %>% 
    ggplot(aes(x = reorder(state, desc(month_avg)), y = month_avg)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='purple') +
    labs(
        title = "Trump's Raw Vote Margin", 
        x = "Northeaster States", 
        y = "Percent Difference") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

margin_plot4 = 
  vote_margin %>%
    filter(Region == "Midwest") %>% 
    ggplot(aes(x = reorder(state, desc(month_avg)), y = month_avg)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='dark red') +
    labs(
        title = "Trump's Vote Margin", 
        x = "Midwestern States", 
        y = "Percent Difference") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

##Combine Plots 
margin_plot1 + margin_plot2 + margin_plot3 + margin_plot4

```

Potential Line graph?
Map with Plotly: Total votes, number of votes, and proportion of votes for each candidate 



































```{r Biden_polls}

biden_df = 
  polls_merge %>% 
  select (state, Region, month, day, biden_winstate, biden_voteshare) %>% 
  group_by(Region, state, month) %>%     
  summarize(
    avgwinstate = mean(biden_winstate),
    avgvoteshare = mean(biden_voteshare),
  ) %>% 
  filter(month == 11) %>% 
  view ()
  
biden_state = 
   biden_df %>%
    ggplot(aes(reorder(state, desc(avgwinstate)), y = avgwinstate)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    labs(
        title = "Biden's Chance to Win States", 
        x = "US States", 
        y = "Percent") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

biden_state = 
  biden_df %>%
    filter(Region == "Northeast") %>% 
    plot_ly(
    x = ~state, y = ~avgwinstate, color = ~state, 
    type = "bar", colors = "viridis")


biden_vote = 
    biden_df %>%
    ggplot(aes(reorder(state, desc(avgvoteshare)), y = avgvoteshare)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='dark blue') +
    labs(
        title = "Biden's Proportion of Votes by State", 
        x = "US States", 
        y = "Percent") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5)) 

```


```{r Trump_polls}

trump_df=
  polls_merge %>% 
  select (state, Region, month, day, trump_winstate, trump_voteshare) %>% 
  group_by(Region, state, month) %>%     
  summarize(
    avgwinstate = mean(trump_winstate),
    avgvoteshare = mean(trump_voteshare),
  ) %>% 
  filter(month == 11) %>% 

  view ()
  

Trump_state = 
  trump_df %>%
    ggplot(aes(reorder(state, desc(avgwinstate)), y = avgwinstate)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='dark red') +
    labs(
        title = "Trump's Chance to Win States", 
        x = "US States", 
        y = "Percent") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))

Trump_vote = 
  trump_df %>%
    ggplot(aes(reorder(state, desc(avgvoteshare)), y = avgvoteshare)) +
    geom_bar(stat = "identity", position = position_dodge(), fill='dark red') +
    labs(
        title = "Trump's Proportion of Votes by State", 
        x = "US States", 
        y = "Percent") +
    theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
          plot.title = element_text(hjust = 0.5))
```

